package com.onectrm.akshare.api.generated.stock;

import io.circe.generic.JsonCodec

@JsonCodec
case class B_Stock_profit_sheet_by_report_emResponse(
  SECUCODE: String,
  SECURITY_CODE: String,
  SECURITY_NAME_ABBR: String,
  ORG_CODE: String,
  ORG_TYPE: String,
  REPORT_DATE: String,
  REPORT_TYPE: String,
  REPORT_DATE_NAME: String,
  SECURITY_TYPE_CODE: String,
  NOTICE_DATE: String,
  UPDATE_DATE: String,
  CURRENCY: String,
  TOTAL_OPERATE_INCOME: Double,
  TOTAL_OPERATE_INCOME_YOY: Double,
  OPERATE_INCOME: Double,
  OPERATE_INCOME_YOY: Double,
  INTEREST_INCOME: Double,
  INTEREST_INCOME_YOY: Double,
  EARNED_PREMIUM: Option[String],
  EARNED_PREMIUM_YOY: Option[String],
//                           FEE_COMMISSION_INCOME: Option[String],
//                           FEE_COMMISSION_INCOME_YOY: Option[String],

//                           OTHER_BUSINESS_INCOME: String,
//                           OTHER_BUSINESS_INCOME_YOY: String,
//                           TOI_OTHER: String,
//                           TOI_OTHER_YOY: String,
//                           TOTAL_OPERATE_COST: Double,
//                           TOTAL_OPERATE_COST_YOY: Double,
//                           OPERATE_COST: Double,
//                           OPERATE_COST_YOY: Double,
//                           INTEREST_EXPENSE: Double,
//                           INTEREST_EXPENSE_YOY: Double,
//                           FEE_COMMISSION_EXPENSE: Double,
//                           FEE_COMMISSION_EXPENSE_YOY: Double,
//                           RESEARCH_EXPENSE: Double,
//                           RESEARCH_EXPENSE_YOY: Double,

//                           SURRENDER_VALUE: String,
//                           SURRENDER_VALUE_YOY: String,
//                           NET_COMPENSATE_EXPENSE: String,
//                           NET_COMPENSATE_EXPENSE_YOY: String,
//                           NET_CONTRACT_RESERVE: String,
//                           NET_CONTRACT_RESERVE_YOY: String,
//                           POLICY_BONUS_EXPENSE: String,
//                           POLICY_BONUS_EXPENSE_YOY: String,
//                           REINSURE_EXPENSE: String,
//                           REINSURE_EXPENSE_YOY: String,
//                           OTHER_BUSINESS_COST: String,
//                           OTHER_BUSINESS_COST_YOY: String,
//                           OPERATE_TAX_ADD: Double,
//                           OPERATE_TAX_ADD_YOY: Double,
//                           SALE_EXPENSE: Double,
//                           SALE_EXPENSE_YOY: Double,
//                           MANAGE_EXPENSE: Double,
//                           MANAGE_EXPENSE_YOY: Double,
//                           ME_RESEARCH_EXPENSE: String,
//                           ME_RESEARCH_EXPENSE_YOY: String,
//                           FINANCE_EXPENSE: Double,
//                           FINANCE_EXPENSE_YOY: Double,
//                           FE_INTEREST_EXPENSE: Double,
//                           FE_INTEREST_EXPENSE_YOY: Double,
//                           FE_INTEREST_INCOME: Double,
//                           FE_INTEREST_INCOME_YOY: Double,
//                           ASSET_IMPAIRMENT_LOSS: String,
//                           ASSET_IMPAIRMENT_LOSS_YOY: String,
//                           CREDIT_IMPAIRMENT_LOSS: String,
//                           CREDIT_IMPAIRMENT_LOSS_YOY: String,
//                           TOC_OTHER: String,
//                           TOC_OTHER_YOY: String,
//                           FAIRVALUE_CHANGE_INCOME: String,
//                           FAIRVALUE_CHANGE_INCOME_YOY: String,
//                           INVEST_INCOME: Int,
//                           INVEST_INCOME_YOY: Double,
//                           INVEST_JOINT_INCOME: String,
//                           INVEST_JOINT_INCOME_YOY: String,
//                           NET_EXPOSURE_INCOME: String,
//                           NET_EXPOSURE_INCOME_YOY: String,
//                           EXCHANGE_INCOME: String,
//                           EXCHANGE_INCOME_YOY: String,
//                           ASSET_DISPOSAL_INCOME: Double,
//                           ASSET_DISPOSAL_INCOME_YOY: String,
//                           ASSET_IMPAIRMENT_INCOME: String,
//                           ASSET_IMPAIRMENT_INCOME_YOY: String,
//                           CREDIT_IMPAIRMENT_INCOME: Double,
//                           CREDIT_IMPAIRMENT_INCOME_YOY: Double,
//                           OTHER_INCOME: Double,
//                           OTHER_INCOME_YOY: Double,
//                           OPERATE_PROFIT_OTHER: String,
//                           OPERATE_PROFIT_OTHER_YOY: String,
//                           OPERATE_PROFIT_BALANCE: Int,
//                           OPERATE_PROFIT_BALANCE_YOY: String,
//                           OPERATE_PROFIT: Double,
//                           OPERATE_PROFIT_YOY: Double,
//                           NONBUSINESS_INCOME: Double,
//                           NONBUSINESS_INCOME_YOY: Double,
//                           NONCURRENT_DISPOSAL_INCOME: String,
//                           NONCURRENT_DISPOSAL_INCOME_YOY: String,
//                           NONBUSINESS_EXPENSE: Double,
//                           NONBUSINESS_EXPENSE_YOY: Double,
//                           NONCURRENT_DISPOSAL_LOSS: String,
//                           NONCURRENT_DISPOSAL_LOSS_YOY: String,
//                           EFFECT_TP_OTHER: String,
//                           EFFECT_TP_OTHER_YOY: String,
//                           TOTAL_PROFIT_BALANCE: Int,
//                           TOTAL_PROFIT_BALANCE_YOY: String,
//                           TOTAL_PROFIT: Double,
//                           TOTAL_PROFIT_YOY: Double,
//                           INCOME_TAX: Double,
//                           INCOME_TAX_YOY: Double,
//                           EFFECT_NETPROFIT_OTHER: String,
//                           EFFECT_NETPROFIT_OTHER_YOY: String,
//                           EFFECT_NETPROFIT_BALANCE: String,
//                           EFFECT_NETPROFIT_BALANCE_YOY: String,
//                           UNCONFIRM_INVEST_LOSS: String,
//                           UNCONFIRM_INVEST_LOSS_YOY: String,
//                           NETPROFIT: Double,
//                           NETPROFIT_YOY: Double,
//                           PRECOMBINE_PROFIT: String,
//                           PRECOMBINE_PROFIT_YOY: String,
//                           CONTINUED_NETPROFIT: Double,
//                           CONTINUED_NETPROFIT_YOY: Double,
//                           DISCONTINUED_NETPROFIT: String,
//                           DISCONTINUED_NETPROFIT_YOY: String,
//                           PARENT_NETPROFIT: Double,
//                           PARENT_NETPROFIT_YOY: Double,
//                           MINORITY_INTEREST: Double,
//                           MINORITY_INTEREST_YOY: Double,
  DEDUCT_PARENT_NETPROFIT: Double,
  DEDUCT_PARENT_NETPROFIT_YOY: Double
//                           NETPROFIT_OTHER: String,
//                           NETPROFIT_OTHER_YOY: String,
//                           NETPROFIT_BALANCE: String,
//                           NETPROFIT_BALANCE_YOY: String,
//                           BASIC_EPS: Double,
//                           BASIC_EPS_YOY: Double,
//                           DILUTED_EPS: Double,
//                           DILUTED_EPS_YOY: Double,
//                           OTHER_COMPRE_INCOME: Double,
//                           OTHER_COMPRE_INCOME_YOY: Double,
//                           PARENT_OCI: Double,
//                           PARENT_OCI_YOY: Double,
//                           MINORITY_OCI: String,
//                           MINORITY_OCI_YOY: String,
//                           PARENT_OCI_OTHER: String,
//                           PARENT_OCI_OTHER_YOY: String,
//                           PARENT_OCI_BALANCE: String,
//                           PARENT_OCI_BALANCE_YOY: String,
//                           UNABLE_OCI: String,
//                           UNABLE_OCI_YOY: String,
//                           CREDITRISK_FAIRVALUE_CHANGE: String,
//                           CREDITRISK_FAIRVALUE_CHANGE_YOY: String,
//                           OTHERRIGHT_FAIRVALUE_CHANGE: String,
//                           OTHERRIGHT_FAIRVALUE_CHANGE_YOY: String,
//                           SETUP_PROFIT_CHANGE: String,
//                           SETUP_PROFIT_CHANGE_YOY: String,
//                           RIGHTLAW_UNABLE_OCI: String,
//                           RIGHTLAW_UNABLE_OCI_YOY: String,
//                           UNABLE_OCI_OTHER: String,
//                           UNABLE_OCI_OTHER_YOY: String,
//                           UNABLE_OCI_BALANCE: String,
//                           UNABLE_OCI_BALANCE_YOY: String,
//                           ABLE_OCI: Double,
//                           ABLE_OCI_YOY: Double,
//                           RIGHTLAW_ABLE_OCI: String,
//                           RIGHTLAW_ABLE_OCI_YOY: String,
//                           AFA_FAIRVALUE_CHANGE: String,
//                           AFA_FAIRVALUE_CHANGE_YOY: String,
//                           HMI_AFA: String,
//                           HMI_AFA_YOY: String,
//                           CASHFLOW_HEDGE_VALID: String,
//                           CASHFLOW_HEDGE_VALID_YOY: String,
//                           CREDITOR_FAIRVALUE_CHANGE: String,
//                           CREDITOR_FAIRVALUE_CHANGE_YOY: String,
//                           CREDITOR_IMPAIRMENT_RESERVE: String,
//                           CREDITOR_IMPAIRMENT_RESERVE_YOY: String,
//                           FINANCE_OCI_AMT: String,
//                           FINANCE_OCI_AMT_YOY: String,
//                           CONVERT_DIFF: Double,
//                           CONVERT_DIFF_YOY: Double,
//                           ABLE_OCI_OTHER: String,
//                           ABLE_OCI_OTHER_YOY: String,
//                           ABLE_OCI_BALANCE: String,
//                           ABLE_OCI_BALANCE_YOY: String,
//                           OCI_OTHER: String,
//                           OCI_OTHER_YOY: String,
//                           OCI_BALANCE: String,
//                           OCI_BALANCE_YOY: String,
//                           TOTAL_COMPRE_INCOME: Double,
//                           TOTAL_COMPRE_INCOME_YOY: Double,
//                           PARENT_TCI: Double,
//                           PARENT_TCI_YOY: Double,
//                           MINORITY_TCI: Double,
//                           MINORITY_TCI_YOY: Double,
//                           PRECOMBINE_TCI: String,
//                           PRECOMBINE_TCI_YOY: String,
//                           EFFECT_TCI_BALANCE: String,
//                           EFFECT_TCI_BALANCE_YOY: String,
//                           TCI_OTHER: String,
//                           TCI_OTHER_YOY: String,
//                           TCI_BALANCE: String,
//                           TCI_BALANCE_YOY: String,
//                           ACF_END_INCOME: String,
//                           ACF_END_INCOME_YOY: String,
//                           OPINION_TYPE: String
)
